"use client";

import { useState, useEffect, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import {
  Activity,
  MessageSquare,
  Users,
  AlertTriangle,
  CheckCircle,
  Clock,
  Search,
  Filter,
  RefreshCw,
  Eye,
  MessageCircle,
  User,
  Bot,
  Zap,
  Database,
  Signal,
  AlertCircle,
  TrendingUp,
  TrendingDown,
  Minus
} from 'lucide-react';
import { useWebSocketContext } from '@/components/websocket/websocket-provider';
import { ConnectionStatus } from '@/components/websocket/connection-status';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';

interface ActiveConversation {
  id: string;
  chatbotId: string;
  chatbotName: string;
  userId: string;
  userName: string;
  status: 'active' | 'idle' | 'ended';
  lastActivity: string;
  messageCount: number;
  duration: number;
  isTyping: boolean;
  currentTopic: string;
  averageResponseTime: number;
  satisfaction?: number;
}

interface SystemMetric {
  id: string;
  name: string;
  value: number;
  unit: string;
  status: 'healthy' | 'warning' | 'critical';
  trend: 'up' | 'down' | 'stable';
  lastUpdate: string;
  threshold: {
    warning: number;
    critical: number;
  };
  history: Array<{
    timestamp: string;
    value: number;
  }>;
}

interface SystemHealthCheck {
  id: string;
  service: string;
  status: 'healthy' | 'warning' | 'critical' | 'unknown';
  responseTime: number;
  lastCheck: string;
  uptime: number;
  errorRate: number;
  dependencies: string[];
}

interface UserActivity {
  id: string;
  userId: string;
  userName: string;
  action: string;
  timestamp: string;
  details: Record<string, any>;
  severity: 'info' | 'warning' | 'error';
}

interface AlertNotification {
  id: string;
  type: 'system' | 'conversation' | 'user' | 'performance';
  severity: 'low' | 'medium' | 'high' | 'critical';
  title: string;
  message: string;
  timestamp: string;
  isRead: boolean;
  actionRequired: boolean;
  autoGenerated: boolean;
  source: string;
  affectedServices: string[];
  resolutionSteps?: string[];
  estimatedImpact: 'none' | 'low' | 'medium' | 'high';
  acknowledged: boolean;
  acknowledgedBy?: string;
  acknowledgedAt?: string;
  resolved: boolean;
  resolvedAt?: string;
  resolvedBy?: string;
}

export default function MonitoringDashboard() {
  const { isConnected, connectionState, joinRoom, leaveRoom } = useWebSocketContext();
  const { toast } = useToast();

  // State
  const [activeConversations, setActiveConversations] = useState<ActiveConversation[]>([]);
  const [systemMetrics, setSystemMetrics] = useState<SystemMetric[]>([]);
  const [systemHealthChecks, setSystemHealthChecks] = useState<SystemHealthCheck[]>([]);
  const [userActivities, setUserActivities] = useState<UserActivity[]>([]);
  const [alerts, setAlerts] = useState<AlertNotification[]>([]);
  const [liveMonitoringEnabled, setLiveMonitoringEnabled] = useState(true);
  const [lastUpdated, setLastUpdated] = useState<Date>(new Date());
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedConversation, setSelectedConversation] = useState<string | null>(null);
  const [autoRefresh, setAutoRefresh] = useState(true);
  const [systemOverallHealth, setSystemOverallHealth] = useState<'healthy' | 'warning' | 'critical'>('healthy');

  // Join monitoring room when connected
  useEffect(() => {
    if (isConnected && liveMonitoringEnabled) {
      const roomId = 'admin:monitoring:live';
      joinRoom(roomId, 'monitoring');

      return () => {
        leaveRoom(roomId);
      };
    }
  }, [isConnected, liveMonitoringEnabled, joinRoom, leaveRoom]);

  // Simulate real-time monitoring data
  const generateMockData = useCallback(() => {
    // Generate active conversations
    const conversations: ActiveConversation[] = Array.from({ length: 8 }, (_, i) => ({
      id: `conv_${i + 1}`,
      chatbotId: `bot_${Math.floor(Math.random() * 3) + 1}`,
      chatbotName: ['Customer Support Bot', 'Sales Assistant', 'Technical Help'][Math.floor(Math.random() * 3)],
      userId: `user_${i + 1}`,
      userName: `User ${i + 1}`,
      status: ['active', 'idle', 'active'][Math.floor(Math.random() * 3)] as 'active' | 'idle' | 'ended',
      lastActivity: new Date(Date.now() - Math.random() * 300000).toISOString(),
      messageCount: Math.floor(Math.random() * 50) + 5,
      duration: Math.floor(Math.random() * 1800) + 60, // 1-30 minutes
      isTyping: Math.random() > 0.7,
      currentTopic: ['Product Inquiry', 'Technical Issue', 'Billing Question', 'General Support'][Math.floor(Math.random() * 4)],
      averageResponseTime: Math.floor(Math.random() * 5000) + 500,
      satisfaction: Math.random() > 0.3 ? Math.floor(Math.random() * 5) + 1 : undefined
    }));

    // Generate system metrics with enhanced health monitoring
    const generateMetricValue = (baseValue: number, variance: number = 0.2) => {
      return Math.max(0, baseValue * (1 + (Math.random() - 0.5) * variance));
    };

    const metrics: SystemMetric[] = [
      {
        id: 'response_time',
        name: 'Avg Response Time',
        value: generateMetricValue(800, 0.5),
        unit: 'ms',
        status: 'healthy',
        trend: ['up', 'down', 'stable'][Math.floor(Math.random() * 3)] as 'up' | 'down' | 'stable',
        lastUpdate: new Date().toISOString(),
        threshold: { warning: 1000, critical: 2000 },
        history: Array.from({ length: 20 }, (_, i) => ({
          timestamp: new Date(Date.now() - (19 - i) * 60000).toISOString(),
          value: generateMetricValue(800, 0.3)
        }))
      },
      {
        id: 'active_sessions',
        name: 'Active Sessions',
        value: conversations.filter(c => c.status === 'active').length,
        unit: '',
        status: 'healthy',
        trend: 'stable',
        lastUpdate: new Date().toISOString(),
        threshold: { warning: 100, critical: 200 },
        history: Array.from({ length: 20 }, (_, i) => ({
          timestamp: new Date(Date.now() - (19 - i) * 60000).toISOString(),
          value: Math.floor(generateMetricValue(8, 0.4))
        }))
      },
      {
        id: 'message_rate',
        name: 'Messages/Min',
        value: generateMetricValue(45, 0.6),
        unit: '/min',
        status: Math.random() > 0.2 ? 'healthy' : 'warning',
        trend: ['up', 'down', 'stable'][Math.floor(Math.random() * 3)] as 'up' | 'down' | 'stable',
        lastUpdate: new Date().toISOString(),
        threshold: { warning: 80, critical: 120 },
        history: Array.from({ length: 20 }, (_, i) => ({
          timestamp: new Date(Date.now() - (19 - i) * 60000).toISOString(),
          value: generateMetricValue(45, 0.4)
        }))
      },
      {
        id: 'error_rate',
        name: 'Error Rate',
        value: generateMetricValue(2.1, 0.8),
        unit: '%',
        status: Math.random() > 0.1 ? 'healthy' : 'critical',
        trend: ['up', 'down', 'stable'][Math.floor(Math.random() * 3)] as 'up' | 'down' | 'stable',
        lastUpdate: new Date().toISOString(),
        threshold: { warning: 5, critical: 10 },
        history: Array.from({ length: 20 }, (_, i) => ({
          timestamp: new Date(Date.now() - (19 - i) * 60000).toISOString(),
          value: generateMetricValue(2.1, 0.6)
        }))
      },
      {
        id: 'cpu_usage',
        name: 'CPU Usage',
        value: generateMetricValue(35, 0.4),
        unit: '%',
        status: 'healthy',
        trend: 'stable',
        lastUpdate: new Date().toISOString(),
        threshold: { warning: 70, critical: 90 },
        history: Array.from({ length: 20 }, (_, i) => ({
          timestamp: new Date(Date.now() - (19 - i) * 60000).toISOString(),
          value: generateMetricValue(35, 0.3)
        }))
      },
      {
        id: 'memory_usage',
        name: 'Memory Usage',
        value: generateMetricValue(58, 0.3),
        unit: '%',
        status: Math.random() > 0.2 ? 'healthy' : 'warning',
        trend: ['up', 'down', 'stable'][Math.floor(Math.random() * 3)] as 'up' | 'down' | 'stable',
        lastUpdate: new Date().toISOString(),
        threshold: { warning: 80, critical: 95 },
        history: Array.from({ length: 20 }, (_, i) => ({
          timestamp: new Date(Date.now() - (19 - i) * 60000).toISOString(),
          value: generateMetricValue(58, 0.25)
        }))
      },
      {
        id: 'disk_usage',
        name: 'Disk Usage',
        value: generateMetricValue(42, 0.1),
        unit: '%',
        status: 'healthy',
        trend: 'stable',
        lastUpdate: new Date().toISOString(),
        threshold: { warning: 85, critical: 95 },
        history: Array.from({ length: 20 }, (_, i) => ({
          timestamp: new Date(Date.now() - (19 - i) * 60000).toISOString(),
          value: generateMetricValue(42, 0.1)
        }))
      },
      {
        id: 'network_latency',
        name: 'Network Latency',
        value: generateMetricValue(25, 0.4),
        unit: 'ms',
        status: 'healthy',
        trend: ['up', 'down', 'stable'][Math.floor(Math.random() * 3)] as 'up' | 'down' | 'stable',
        lastUpdate: new Date().toISOString(),
        threshold: { warning: 100, critical: 200 },
        history: Array.from({ length: 20 }, (_, i) => ({
          timestamp: new Date(Date.now() - (19 - i) * 60000).toISOString(),
          value: generateMetricValue(25, 0.3)
        }))
      }
    ];

    // Update status based on thresholds
    metrics.forEach(metric => {
      if (metric.value >= metric.threshold.critical) {
        metric.status = 'critical';
      } else if (metric.value >= metric.threshold.warning) {
        metric.status = 'warning';
      } else {
        metric.status = 'healthy';
      }
    });

    // Generate system health checks
    const healthChecks: SystemHealthCheck[] = [
      {
        id: 'api_gateway',
        service: 'API Gateway',
        status: Math.random() > 0.05 ? 'healthy' : 'warning',
        responseTime: generateMetricValue(150, 0.4),
        lastCheck: new Date().toISOString(),
        uptime: 99.95 + Math.random() * 0.05,
        errorRate: generateMetricValue(0.8, 0.6),
        dependencies: ['Load Balancer', 'Backend Services']
      },
      {
        id: 'database',
        service: 'PostgreSQL Database',
        status: Math.random() > 0.02 ? 'healthy' : 'critical',
        responseTime: generateMetricValue(45, 0.3),
        lastCheck: new Date().toISOString(),
        uptime: 99.98 + Math.random() * 0.02,
        errorRate: generateMetricValue(0.2, 0.5),
        dependencies: ['Storage', 'Network']
      },
      {
        id: 'redis_cache',
        service: 'Redis Cache',
        status: Math.random() > 0.03 ? 'healthy' : 'warning',
        responseTime: generateMetricValue(8, 0.5),
        lastCheck: new Date().toISOString(),
        uptime: 99.92 + Math.random() * 0.08,
        errorRate: generateMetricValue(0.5, 0.4),
        dependencies: ['Memory', 'Network']
      },
      {
        id: 'websocket_service',
        service: 'WebSocket Service',
        status: Math.random() > 0.04 ? 'healthy' : 'warning',
        responseTime: generateMetricValue(20, 0.6),
        lastCheck: new Date().toISOString(),
        uptime: 99.89 + Math.random() * 0.11,
        errorRate: generateMetricValue(1.2, 0.7),
        dependencies: ['API Gateway', 'Load Balancer']
      },
      {
        id: 'ai_service',
        service: 'AI/LLM Service',
        status: Math.random() > 0.06 ? 'healthy' : 'warning',
        responseTime: generateMetricValue(1200, 0.4),
        lastCheck: new Date().toISOString(),
        uptime: 99.85 + Math.random() * 0.15,
        errorRate: generateMetricValue(2.1, 0.5),
        dependencies: ['External API', 'Network']
      },
      {
        id: 'file_storage',
        service: 'File Storage',
        status: Math.random() > 0.02 ? 'healthy' : 'warning',
        responseTime: generateMetricValue(95, 0.3),
        lastCheck: new Date().toISOString(),
        uptime: 99.96 + Math.random() * 0.04,
        errorRate: generateMetricValue(0.3, 0.4),
        dependencies: ['Storage', 'Network']
      }
    ];

    // Calculate overall system health
    const criticalServices = healthChecks.filter(h => h.status === 'critical').length;
    const warningServices = healthChecks.filter(h => h.status === 'warning').length;
    const criticalMetrics = metrics.filter(m => m.status === 'critical').length;
    const warningMetrics = metrics.filter(m => m.status === 'warning').length;

    let overallHealth: 'healthy' | 'warning' | 'critical' = 'healthy';
    if (criticalServices > 0 || criticalMetrics > 2) {
      overallHealth = 'critical';
    } else if (warningServices > 1 || warningMetrics > 2) {
      overallHealth = 'warning';
    }

    // Generate user activities
    const activities: UserActivity[] = Array.from({ length: 15 }, (_, i) => ({
      id: `activity_${i + 1}`,
      userId: `user_${Math.floor(Math.random() * 10) + 1}`,
      userName: `User ${Math.floor(Math.random() * 10) + 1}`,
      action: ['Message Sent', 'Conversation Started', 'Conversation Ended', 'File Uploaded', 'Feedback Submitted'][Math.floor(Math.random() * 5)],
      timestamp: new Date(Date.now() - Math.random() * 3600000).toISOString(),
      details: {
        conversationId: `conv_${Math.floor(Math.random() * 5) + 1}`,
        botId: `bot_${Math.floor(Math.random() * 3) + 1}`
      },
      severity: ['info', 'warning', 'error'][Math.floor(Math.random() * 3)] as 'info' | 'warning' | 'error'
    }));

    // Generate enhanced alerts with critical issue detection
    const generateCriticalAlerts = () => {
      const criticalAlerts = [];

      // Check for critical metrics and services
      const criticalMetricAlerts = metrics.filter(m => m.status === 'critical').map(metric => ({
        type: 'system',
        title: `Critical: ${metric.name} Alert`,
        message: `${metric.name} has reached critical level: ${metric.value.toFixed(2)}${metric.unit} (threshold: ${metric.threshold.critical}${metric.unit})`,
        severity: 'critical' as const,
        source: `System Metrics - ${metric.name}`,
        affectedServices: ['Backend Services', 'User Experience'],
        estimatedImpact: 'high' as const,
        resolutionSteps: [
          'Investigate system resources immediately',
          'Check for memory leaks or CPU-intensive processes',
          'Scale up resources if needed',
          'Contact system administrator'
        ]
      }));

      const criticalServiceAlerts = healthChecks.filter(h => h.status === 'critical').map(service => ({
        type: 'system',
        title: `Critical: ${service.service} Down`,
        message: `${service.service} is experiencing critical issues with ${service.errorRate.toFixed(2)}% error rate`,
        severity: 'critical' as const,
        source: `Health Check - ${service.service}`,
        affectedServices: [service.service, ...service.dependencies],
        estimatedImpact: 'high' as const,
        resolutionSteps: [
          'Check service status immediately',
          'Verify dependencies are operational',
          'Restart service if necessary',
          'Investigate error logs'
        ]
      }));

      criticalAlerts.push(...criticalMetricAlerts, ...criticalServiceAlerts);
      return criticalAlerts;
    };

    const automaticAlerts = generateCriticalAlerts();

    // Generate additional sample alerts
    const sampleAlertMessages = [
      {
        type: 'system',
        title: 'High Memory Usage',
        message: 'Memory usage has exceeded warning threshold',
        severity: 'medium',
        source: 'System Monitor',
        affectedServices: ['Backend Services'],
        estimatedImpact: 'medium',
        resolutionSteps: ['Monitor memory usage', 'Check for memory leaks', 'Consider scaling']
      },
      {
        type: 'conversation',
        title: 'Slow Response Time',
        message: 'Average response time increased significantly',
        severity: 'high',
        source: 'Performance Monitor',
        affectedServices: ['AI Service', 'Database'],
        estimatedImpact: 'high',
        resolutionSteps: ['Check AI service status', 'Optimize database queries', 'Review system load']
      },
      {
        type: 'user',
        title: 'Authentication Failures',
        message: 'Unusual number of failed login attempts detected',
        severity: 'medium',
        source: 'Security Monitor',
        affectedServices: ['Authentication Service'],
        estimatedImpact: 'low',
        resolutionSteps: ['Review security logs', 'Check for brute force attacks', 'Consider rate limiting']
      },
      {
        type: 'performance',
        title: 'Database Connection Pool',
        message: 'Database connection pool approaching limit',
        severity: 'high',
        source: 'Database Monitor',
        affectedServices: ['Database', 'Backend Services'],
        estimatedImpact: 'high',
        resolutionSteps: ['Increase connection pool size', 'Optimize long-running queries', 'Check for connection leaks']
      }
    ];

    const sampleAlerts = Array.from({ length: 4 }, (_, i) => {
      const alertTemplate = sampleAlertMessages[i % sampleAlertMessages.length];
      return {
        id: `sample_alert_${i + 1}`,
        type: alertTemplate.type as 'system' | 'conversation' | 'user' | 'performance',
        severity: alertTemplate.severity as 'low' | 'medium' | 'high' | 'critical',
        title: alertTemplate.title,
        message: alertTemplate.message,
        timestamp: new Date(Date.now() - Math.random() * 7200000).toISOString(),
        isRead: Math.random() > 0.4,
        actionRequired: alertTemplate.severity === 'critical' || alertTemplate.severity === 'high',
        autoGenerated: true,
        source: alertTemplate.source,
        affectedServices: alertTemplate.affectedServices,
        resolutionSteps: alertTemplate.resolutionSteps,
        estimatedImpact: alertTemplate.estimatedImpact as 'none' | 'low' | 'medium' | 'high',
        acknowledged: Math.random() > 0.7,
        acknowledgedBy: Math.random() > 0.5 ? 'admin@example.com' : undefined,
        acknowledgedAt: Math.random() > 0.5 ? new Date(Date.now() - Math.random() * 3600000).toISOString() : undefined,
        resolved: Math.random() > 0.8,
        resolvedAt: Math.random() > 0.9 ? new Date(Date.now() - Math.random() * 1800000).toISOString() : undefined,
        resolvedBy: Math.random() > 0.9 ? 'admin@example.com' : undefined
      };
    });

    // Combine automatic critical alerts with sample alerts
    const newAlerts: AlertNotification[] = [
      ...automaticAlerts.map((alert, i) => ({
        id: `critical_alert_${i + 1}`,
        ...alert,
        timestamp: new Date(Date.now() - Math.random() * 300000).toISOString(), // Recent alerts
        isRead: false, // Critical alerts should be unread
        actionRequired: true,
        autoGenerated: true,
        acknowledged: false,
        resolved: false
      })),
      ...sampleAlerts
    ];

    setActiveConversations(conversations);
    setSystemMetrics(metrics);
    setSystemHealthChecks(healthChecks);
    setUserActivities(activities);
    setAlerts(newAlerts);
    setSystemOverallHealth(overallHealth);
    setLastUpdated(new Date());
  }, []);

  // Real-time updates
  useEffect(() => {
    generateMockData();

    if (autoRefresh && liveMonitoringEnabled) {
      const interval = setInterval(generateMockData, 3000);
      return () => clearInterval(interval);
    }
  }, [autoRefresh, liveMonitoringEnabled, generateMockData]);

  // Filter conversations based on search
  const filteredConversations = activeConversations.filter(conv =>
    conv.userName.toLowerCase().includes(searchTerm.toLowerCase()) ||
    conv.chatbotName.toLowerCase().includes(searchTerm.toLowerCase()) ||
    conv.currentTopic.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const formatDuration = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const formatTimestamp = (timestamp: string) => {
    return new Date(timestamp).toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-green-500';
      case 'idle': return 'bg-yellow-500';
      case 'ended': return 'bg-gray-500';
      case 'healthy': return 'text-green-600';
      case 'warning': return 'text-yellow-600';
      case 'critical': return 'text-red-600';
      default: return 'bg-gray-500';
    }
  };

  const getTrendIcon = (trend: string) => {
    switch (trend) {
      case 'up': return <TrendingUp className="w-3 h-3 text-green-500" />;
      case 'down': return <TrendingDown className="w-3 h-3 text-red-500" />;
      case 'stable': return <Minus className="w-3 h-3 text-gray-500" />;
      default: return null;
    }
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'low': return 'bg-blue-100 text-blue-800';
      case 'medium': return 'bg-yellow-100 text-yellow-800';
      case 'high': return 'bg-orange-100 text-orange-800';
      case 'critical': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getImpactColor = (impact: string) => {
    switch (impact) {
      case 'none': return 'text-gray-500';
      case 'low': return 'text-blue-500';
      case 'medium': return 'text-yellow-500';
      case 'high': return 'text-red-500';
      default: return 'text-gray-500';
    }
  };

  // Alert management functions
  const acknowledgeAlert = (alertId: string) => {
    setAlerts(prev => prev.map(alert =>
      alert.id === alertId
        ? {
            ...alert,
            acknowledged: true,
            acknowledgedBy: 'admin@example.com', // In real app, get from user context
            acknowledgedAt: new Date().toISOString()
          }
        : alert
    ));

    toast({
      title: "Alert Acknowledged",
      description: "Alert has been marked as acknowledged",
      duration: 3000
    });
  };

  const resolveAlert = (alertId: string) => {
    setAlerts(prev => prev.map(alert =>
      alert.id === alertId
        ? {
            ...alert,
            resolved: true,
            resolvedBy: 'admin@example.com', // In real app, get from user context
            resolvedAt: new Date().toISOString()
          }
        : alert
    ));

    toast({
      title: "Alert Resolved",
      description: "Alert has been marked as resolved",
      duration: 3000
    });
  };

  const markAlertAsRead = (alertId: string) => {
    setAlerts(prev => prev.map(alert =>
      alert.id === alertId ? { ...alert, isRead: true } : alert
    ));
  };

  return (
    <div className="flex-1 space-y-4 p-4 md:p-8 pt-6">
      {/* Header */}
      <div className="flex items-center justify-between space-y-2">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Live Monitoring</h2>
          <p className="text-muted-foreground">
            Real-time monitoring of conversations, system health, and user activities
          </p>
        </div>
        <div className="flex items-center gap-4">
          <ConnectionStatus
            compact
            showQualityIndicator={true}
            showAutoReconnect={true}
          />
          <div className="flex items-center space-x-2">
            <div className={`w-2 h-2 rounded-full ${isConnected && liveMonitoringEnabled ? 'bg-green-500 animate-pulse' : 'bg-gray-400'}`} />
            <Label className="text-sm">
              {isConnected && liveMonitoringEnabled ? 'Live' : 'Offline'}
            </Label>
          </div>
          <div className="flex items-center space-x-2">
            <Switch
              id="live-monitoring"
              checked={liveMonitoringEnabled}
              onCheckedChange={setLiveMonitoringEnabled}
            />
            <Label htmlFor="live-monitoring" className="text-sm">
              Live Monitoring
            </Label>
          </div>
          <div className="flex items-center space-x-2">
            <Switch
              id="auto-refresh"
              checked={autoRefresh}
              onCheckedChange={setAutoRefresh}
            />
            <Label htmlFor="auto-refresh" className="text-sm">
              Auto Refresh
            </Label>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={generateMockData}
            disabled={!liveMonitoringEnabled}
          >
            <RefreshCw className="w-4 h-4 mr-2" />
            Refresh
          </Button>
        </div>
      </div>

      {/* Quick Stats */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Active Conversations</CardTitle>
            <MessageCircle className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{activeConversations.filter(c => c.status === 'active').length}</div>
            <p className="text-xs text-muted-foreground">
              {activeConversations.filter(c => c.isTyping).length} users typing
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">System Health</CardTitle>
            <Activity className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className={cn(
              "text-2xl font-bold",
              systemOverallHealth === 'healthy' ? 'text-green-600' :
              systemOverallHealth === 'warning' ? 'text-yellow-600' : 'text-red-600'
            )}>
              {systemOverallHealth === 'healthy' ? 'Healthy' :
               systemOverallHealth === 'warning' ? 'Warning' : 'Critical'}
            </div>
            <p className="text-xs text-muted-foreground">
              {systemHealthChecks.filter(h => h.status === 'healthy').length}/{systemHealthChecks.length} services healthy
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Unread Alerts</CardTitle>
            <AlertTriangle className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-orange-600">{alerts.filter(a => !a.isRead).length}</div>
            <p className="text-xs text-muted-foreground">
              {alerts.filter(a => a.severity === 'critical' && !a.isRead).length} critical
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Last Updated</CardTitle>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{formatTimestamp(lastUpdated.toISOString())}</div>
            <p className="text-xs text-muted-foreground">
              Auto-refresh: {autoRefresh ? 'On' : 'Off'}
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Main Content */}
      <Tabs defaultValue="conversations" className="space-y-4">
        <TabsList>
          <TabsTrigger value="conversations">Live Conversations</TabsTrigger>
          <TabsTrigger value="metrics">System Metrics</TabsTrigger>
          <TabsTrigger value="health">Health Checks</TabsTrigger>
          <TabsTrigger value="activities">User Activities</TabsTrigger>
          <TabsTrigger value="alerts">Alerts</TabsTrigger>
        </TabsList>

        <TabsContent value="conversations" className="space-y-4">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle>Active Conversations</CardTitle>
                <div className="flex items-center gap-2">
                  <div className="relative">
                    <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                    <Input
                      placeholder="Search conversations..."
                      value={searchTerm}
                      onChange={(e) => setSearchTerm(e.target.value)}
                      className="pl-8 w-64"
                    />
                  </div>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <ScrollArea className="h-[600px]">
                <div className="space-y-4">
                  {filteredConversations.map((conversation) => (
                    <div
                      key={conversation.id}
                      className={cn(
                        "p-4 border rounded-lg cursor-pointer transition-colors",
                        selectedConversation === conversation.id ? "border-primary bg-primary/5" : "hover:bg-muted/50"
                      )}
                      onClick={() => setSelectedConversation(conversation.id)}
                    >
                      <div className="flex items-start justify-between">
                        <div className="space-y-2">
                          <div className="flex items-center gap-2">
                            <div className={`w-2 h-2 rounded-full ${getStatusColor(conversation.status)}`} />
                            <span className="font-medium">{conversation.userName}</span>
                            <Badge variant="outline" className="text-xs">
                              {conversation.chatbotName}
                            </Badge>
                            {conversation.isTyping && (
                              <Badge variant="secondary" className="text-xs animate-pulse">
                                Typing...
                              </Badge>
                            )}
                          </div>
                          <div className="text-sm text-muted-foreground">
                            Topic: {conversation.currentTopic}
                          </div>
                          <div className="flex items-center gap-4 text-xs text-muted-foreground">
                            <span>{conversation.messageCount} messages</span>
                            <span>Duration: {formatDuration(conversation.duration)}</span>
                            <span>Avg response: {conversation.averageResponseTime}ms</span>
                            {conversation.satisfaction && (
                              <span>Rating: {conversation.satisfaction}/5 ⭐</span>
                            )}
                          </div>
                        </div>
                        <div className="text-right text-sm text-muted-foreground">
                          <div>Last activity</div>
                          <div>{formatTimestamp(conversation.lastActivity)}</div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </ScrollArea>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="metrics" className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {systemMetrics.map((metric) => (
              <Card key={metric.id}>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                  <CardTitle className="text-sm font-medium">{metric.name}</CardTitle>
                  <div className="flex items-center gap-1">
                    {getTrendIcon(metric.trend)}
                    <Database className="h-4 w-4 text-muted-foreground" />
                  </div>
                </CardHeader>
                <CardContent>
                  <div className={cn("text-2xl font-bold", getStatusColor(metric.status))}>
                    {typeof metric.value === 'number' && metric.value % 1 !== 0
                      ? metric.value.toFixed(2)
                      : metric.value}{metric.unit}
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Status: <span className={getStatusColor(metric.status)}>{metric.status}</span>
                  </p>
                  <p className="text-xs text-muted-foreground">
                    Thresholds: Warning {metric.threshold.warning}{metric.unit}, Critical {metric.threshold.critical}{metric.unit}
                  </p>
                  <p className="text-xs text-muted-foreground">
                    Updated: {formatTimestamp(metric.lastUpdate)}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>

        <TabsContent value="health" className="space-y-4">
          <div className="grid gap-4 md:grid-cols-1 lg:grid-cols-2">
            {systemHealthChecks.map((check) => (
              <Card key={check.id}>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-lg">{check.service}</CardTitle>
                    <div className="flex items-center gap-2">
                      <div className={cn(
                        "w-3 h-3 rounded-full",
                        check.status === 'healthy' ? 'bg-green-500' :
                        check.status === 'warning' ? 'bg-yellow-500' :
                        check.status === 'critical' ? 'bg-red-500' : 'bg-gray-500'
                      )} />
                      <span className={cn(
                        "text-sm font-medium",
                        getStatusColor(check.status)
                      )}>
                        {check.status.toUpperCase()}
                      </span>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <div className="text-sm text-muted-foreground">Response Time</div>
                      <div className="text-lg font-semibold">{check.responseTime.toFixed(0)}ms</div>
                    </div>
                    <div>
                      <div className="text-sm text-muted-foreground">Uptime</div>
                      <div className="text-lg font-semibold">{check.uptime.toFixed(2)}%</div>
                    </div>
                    <div>
                      <div className="text-sm text-muted-foreground">Error Rate</div>
                      <div className="text-lg font-semibold">{check.errorRate.toFixed(2)}%</div>
                    </div>
                    <div>
                      <div className="text-sm text-muted-foreground">Last Check</div>
                      <div className="text-lg font-semibold">{formatTimestamp(check.lastCheck)}</div>
                    </div>
                  </div>
                  {check.dependencies.length > 0 && (
                    <div>
                      <div className="text-sm text-muted-foreground mb-2">Dependencies</div>
                      <div className="flex flex-wrap gap-1">
                        {check.dependencies.map((dep, index) => (
                          <Badge key={index} variant="outline" className="text-xs">
                            {dep}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>

        <TabsContent value="activities" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Recent User Activities</CardTitle>
            </CardHeader>
            <CardContent>
              <ScrollArea className="h-[600px]">
                <div className="space-y-4">
                  {userActivities.map((activity) => (
                    <div key={activity.id} className="flex items-start gap-3 p-3 border rounded-lg">
                      <div className={cn(
                        "w-2 h-2 rounded-full mt-2",
                        activity.severity === 'error' ? 'bg-red-500' :
                        activity.severity === 'warning' ? 'bg-yellow-500' : 'bg-blue-500'
                      )} />
                      <div className="flex-1">
                        <div className="flex items-center justify-between">
                          <div className="font-medium">{activity.action}</div>
                          <div className="text-sm text-muted-foreground">
                            {formatTimestamp(activity.timestamp)}
                          </div>
                        </div>
                        <div className="text-sm text-muted-foreground">
                          User: {activity.userName}
                        </div>
                        {activity.details.conversationId && (
                          <div className="text-xs text-muted-foreground">
                            Conversation: {activity.details.conversationId}
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </ScrollArea>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="alerts" className="space-y-4">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle>System Alerts</CardTitle>
                <div className="flex items-center gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setAlerts(alerts.map(a => ({ ...a, isRead: true })))}
                  >
                    Mark All Read
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setAlerts(alerts.map(a => ({ ...a, acknowledged: true, acknowledgedBy: 'admin@example.com', acknowledgedAt: new Date().toISOString() })))}
                  >
                    Acknowledge All
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <ScrollArea className="h-[600px]">
                <div className="space-y-4">
                  {alerts.map((alert) => (
                    <div
                      key={alert.id}
                      className={cn(
                        "p-4 border rounded-lg",
                        !alert.isRead && "border-l-4 border-l-orange-500 bg-orange-50/50",
                        alert.severity === 'critical' && "border-l-4 border-l-red-500 bg-red-50/30"
                      )}
                      onClick={() => markAlertAsRead(alert.id)}
                    >
                      <div className="space-y-3">
                        {/* Alert Header */}
                        <div className="flex items-start justify-between">
                          <div className="space-y-2">
                            <div className="flex items-center gap-2 flex-wrap">
                              <Badge className={getSeverityColor(alert.severity)}>
                                {alert.severity.toUpperCase()}
                              </Badge>
                              <Badge variant="outline">{alert.type}</Badge>
                              {alert.autoGenerated && (
                                <Badge variant="secondary" className="text-xs">
                                  Auto-Generated
                                </Badge>
                              )}
                              {alert.actionRequired && (
                                <Badge variant="destructive" className="text-xs">
                                  Action Required
                                </Badge>
                              )}
                              {!alert.isRead && (
                                <Badge variant="secondary" className="text-xs">
                                  New
                                </Badge>
                              )}
                              {alert.acknowledged && (
                                <Badge className="bg-green-100 text-green-800 text-xs">
                                  Acknowledged
                                </Badge>
                              )}
                              {alert.resolved && (
                                <Badge className="bg-blue-100 text-blue-800 text-xs">
                                  Resolved
                                </Badge>
                              )}
                            </div>
                            <div className="font-medium">{alert.title}</div>
                            <div className="text-sm text-muted-foreground">
                              {alert.message}
                            </div>
                          </div>
                          <div className="text-sm text-muted-foreground text-right">
                            <div>{formatTimestamp(alert.timestamp)}</div>
                            <div className="text-xs">Source: {alert.source}</div>
                          </div>
                        </div>

                        {/* Alert Details */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                          <div>
                            <div className="text-muted-foreground">Estimated Impact</div>
                            <div className={cn("font-medium", getImpactColor(alert.estimatedImpact))}>
                              {alert.estimatedImpact.toUpperCase()}
                            </div>
                          </div>
                          {alert.affectedServices.length > 0 && (
                            <div>
                              <div className="text-muted-foreground">Affected Services</div>
                              <div className="flex flex-wrap gap-1 mt-1">
                                {alert.affectedServices.slice(0, 3).map((service, index) => (
                                  <Badge key={index} variant="outline" className="text-xs">
                                    {service}
                                  </Badge>
                                ))}
                                {alert.affectedServices.length > 3 && (
                                  <Badge variant="outline" className="text-xs">
                                    +{alert.affectedServices.length - 3} more
                                  </Badge>
                                )}
                              </div>
                            </div>
                          )}
                        </div>

                        {/* Resolution Steps */}
                        {alert.resolutionSteps && alert.resolutionSteps.length > 0 && (
                          <div>
                            <div className="text-sm font-medium text-muted-foreground mb-2">
                              Recommended Actions:
                            </div>
                            <div className="space-y-1">
                              {alert.resolutionSteps.slice(0, 3).map((step, index) => (
                                <div key={index} className="text-xs text-muted-foreground flex items-start gap-2">
                                  <span className="text-primary">{index + 1}.</span>
                                  <span>{step}</span>
                                </div>
                              ))}
                              {alert.resolutionSteps.length > 3 && (
                                <div className="text-xs text-muted-foreground">
                                  ... and {alert.resolutionSteps.length - 3} more steps
                                </div>
                              )}
                            </div>
                          </div>
                        )}

                        {/* Acknowledgment/Resolution Info */}
                        {(alert.acknowledged || alert.resolved) && (
                          <div className="pt-2 border-t space-y-1">
                            {alert.acknowledged && (
                              <div className="text-xs text-muted-foreground">
                                Acknowledged by {alert.acknowledgedBy} at {alert.acknowledgedAt ? formatTimestamp(alert.acknowledgedAt) : 'unknown'}
                              </div>
                            )}
                            {alert.resolved && (
                              <div className="text-xs text-muted-foreground">
                                Resolved by {alert.resolvedBy} at {alert.resolvedAt ? formatTimestamp(alert.resolvedAt) : 'unknown'}
                              </div>
                            )}
                          </div>
                        )}

                        {/* Action Buttons */}
                        {!alert.resolved && (
                          <div className="flex gap-2 pt-2 border-t">
                            {!alert.acknowledged && (
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  acknowledgeAlert(alert.id);
                                }}
                                className="h-8 text-xs"
                              >
                                <CheckCircle className="w-3 h-3 mr-1" />
                                Acknowledge
                              </Button>
                            )}
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={(e) => {
                                e.stopPropagation();
                                resolveAlert(alert.id);
                              }}
                              className="h-8 text-xs"
                            >
                              <CheckCircle className="w-3 h-3 mr-1" />
                              Mark Resolved
                            </Button>
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </ScrollArea>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}