import { NextRequest, NextResponse } from 'next/server';
import { AuthTokenService } from '@/lib/auth';
import { createErrorResponse, createSuccessResponse } from '@/lib/api-utils';
import { db } from '@/lib/db';
import { chatbotPlaygroundSessions, chatbotMessages, chatbotInstances } from '@/lib/db/schema';
import { and, eq } from 'drizzle-orm';
import { randomUUID } from 'crypto';

/**
 * POST /api/v1/chatbots/[id]/playground-sessions/[sessionId]/chat
 *
 * Send a chat message in a playground session
 */
export async function POST(
  request: NextRequest,
  { params }: { params: { id: string; sessionId: string } }
) {
  try {
    // Authenticate user
    const user = await AuthTokenService.verifyRequest(request);
    if (!user) {
      return NextResponse.json(
        createErrorResponse('Authentication required', 'UNAUTHORIZED'),
        { status: 401 }
      );
    }

    const chatbotId = params.id;
    const sessionId = params.sessionId;

    // Parse request body
    let requestData: any;
    try {
      requestData = await request.json();
    } catch (error) {
      return NextResponse.json(
        createErrorResponse('Invalid request body', 'VALIDATION_ERROR'),
        { status: 400 }
      );
    }

    const { message, config_override = {}, include_vector_results = false } = requestData;

    if (!message || typeof message !== 'string' || !message.trim()) {
      return NextResponse.json(
        createErrorResponse('Message is required', 'VALIDATION_ERROR'),
        { status: 400 }
      );
    }

    // Verify session exists and belongs to user
    const session = await db
      .select()
      .from(chatbotPlaygroundSessions)
      .where(
        and(
          eq(chatbotPlaygroundSessions.id, sessionId),
          eq(chatbotPlaygroundSessions.chatbotId, chatbotId),
          eq(chatbotPlaygroundSessions.userId, user.id)
        )
      )
      .limit(1);

    if (!session.length) {
      return NextResponse.json(
        createErrorResponse('Session not found', 'NOT_FOUND'),
        { status: 404 }
      );
    }

    // Get chatbot details
    const chatbot = await db
      .select()
      .from(chatbotInstances)
      .where(eq(chatbotInstances.id, chatbotId))
      .limit(1);

    if (!chatbot.length) {
      return NextResponse.json(
        createErrorResponse('Chatbot not found', 'NOT_FOUND'),
        { status: 404 }
      );
    }

    const startTime = Date.now();

    // Save user message
    const userMessageId = randomUUID();
    await db.insert(chatbotMessages).values({
      id: userMessageId,
      conversationId: sessionId,
      role: 'user',
      content: message.trim(),
      metadata: {
        timestamp: new Date().toISOString(),
        user_id: user.id
      },
      createdAt: new Date(),
    });

    // Simulate AI response (replace with actual AI integration)
    const mockResponse = `Hello! I'm ${chatbot[0].name}. I received your message: "${message.trim()}". This is a simulated response from the playground. In a real implementation, this would be generated by the AI model configured for this chatbot.`;

    const responseTime = Date.now() - startTime;
    const mockTokenUsage = {
      prompt: Math.floor(message.length / 4), // Rough estimate
      completion: Math.floor(mockResponse.length / 4),
      total: Math.floor((message.length + mockResponse.length) / 4)
    };

    // Save assistant message
    const assistantMessageId = randomUUID();
    await db.insert(chatbotMessages).values({
      id: assistantMessageId,
      conversationId: sessionId,
      role: 'assistant',
      content: mockResponse,
      metadata: {
        responseTime,
        tokenUsage: mockTokenUsage,
        model: chatbot[0].model || 'gpt-4',
        temperature: config_override.temperature || 0.7,
        config_override,
        user_id: user.id
      },
      vectorSearchResults: include_vector_results ? [] : null, // Mock vector results
      createdAt: new Date(),
    });

    // Log interaction
    console.log(
      `Playground chat - Session: ${sessionId}, User: ${user.id}, ` +
      `Response time: ${responseTime}ms, Tokens: ${mockTokenUsage.total}`
    );

    return NextResponse.json(
      createSuccessResponse({
        response: mockResponse,
        response_time: responseTime,
        token_usage: mockTokenUsage,
        vector_search_results: include_vector_results ? [] : undefined,
        model: chatbot[0].model || 'gpt-4',
        temperature: config_override.temperature || 0.7,
        session_id: sessionId,
        message_id: assistantMessageId
      }),
      { status: 200 }
    );

  } catch (error) {
    console.error('Error processing chat message:', error);
    return NextResponse.json(
      createErrorResponse('Failed to process message', 'PROCESSING_ERROR'),
      { status: 500 }
    );
  }
}